### ISSUE TITLE
Update list styles

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#767]
**Describe the solution you'd like**

See the [Figma file](https://www.figma.com/file/rQK2dt9eaLOMmvTOf5ifdr/Ethereum.org-Style-Guide-RC1?node-id=602%3A1) style guide for implementation details.

- [ ] Text list (with & without bullets)
- [ ] Link list (with & without bullets)
- [ ] Text & description list (with & without bullets)

**Additional context**

Part #753, the output of #668 (see [Figma file](https://www.figma.com/file/rQK2dt9eaLOMmvTOf5ifdr/Ethereum.org-Style-Guide-RC1?node-id=602%3A1
))

**Comment by carlfairclough** [comment]
@samajammin I'm looking at this right now, and have two approaches. I have a definite preference, but I want to defer here to sense-check things before moving forwards.

I'm looking at the more complex version of the lists right now, and have built this:
![image](https://user-images.githubusercontent.com/4670881/76434194-21b45f00-6394-11ea-8fe7-3322892e5ad2.png)

As it stands, this is a pure css based thing, and is called with the following markdown
```
1. [Getting up to speed on Ethereum _Matt Condon_ _Aug 7, 2017_](https://medium.com/@mattcondon/getting-up-to-speed-on-ethereum-63ed28821bbe)
2. [Ethereum In Depth, Part 1 _Facu Spagnuolo_ _May 11, 2018_](https://blog.openzeppelin.com/ethereum-in-depth-part-1-968981e6f833/)
3. [Ethereum In Depth, Part 2 _Facu Spagnuolo_ _July 24, 2018_](https://blog.openzeppelin.com/ethereum-in-depth-part-2-6339cf6bddb9/)
{.link-list .link-card}
```
I have a couple of concerns with this:
- it's relies on _em_ tags to separate and place content, and I don't think that's a particularly semantic approach
- the markdown is difficult to read

Alternatively, I have this:
```
---
helpfulResources:
  - title: "Getting up to speed on Ethereum"
    author: "Matt Condon"
    date: "Aug 7, 2017"
    link: "https://medium.com/@mattcondon/getting-up-to-speed-on-ethereum-63ed28821bbe"
  - title: "Getting up to speed on Ethereum"
    author: "Matt Condon"
    date: "Aug 7, 2017"
    link: "https://medium.com/@mattcondon/getting-up-to-speed-on-ethereum-63ed28821bbe"
---

# A title

some unrelated markdown content

<link-list :items="$page.frontmatter.helpfulResources" />
```

I have a preference for the frontmatter approach, mainly because it allows us to add information, (i.e. are they dates, or authors, or titles, etc). I think it's much easier to read, but would be a *major * content shift. I just want to get thoughts on one or the other — they aren't mutually exclusive, and neither breaks any legacy content, but it would be great to prioritise one over the other.
